import { useEffect, useMemo, useState } from 'react';
import { FiAlertTriangle, FiClock, FiCpu, FiHardDrive, FiRefreshCw, FiUsers, FiWifi } from 'react-icons/fi';
import { useTenant } from '../../hooks/useTenant';
import { getActiveSessions, getDevices, getProvisioningJobs, getSites } from '../../services/operationsService';
import { PageHeader, SiteBadge, StatCard, StatusBadge } from '../../components/operations/OperationsUI';

function formatUptime(seconds){const n=Number(seconds||0);if(!n)return '—';const d=Math.floor(n/86400),h=Math.floor((n%86400)/3600),m=Math.floor((n%3600)/60);return [d?`${d}d`:null,h?`${h}h`:null,`${m}m`].filter(Boolean).join(' ');}
function lastContact(value){if(!value)return 'Never';const d=new Date(value);if(Number.isNaN(d.getTime()))return 'Never';const diff=Math.max(0,Date.now()-d.getTime()),min=Math.floor(diff/60000);if(min<1)return 'Just now';if(min<60)return `${min} min ago`;const hr=Math.floor(min/60);return hr<24?`${hr} hr ago`:d.toLocaleString();}

function isRouterDevice(device) {
  const type = String(device?.device_type || '').trim().toLowerCase().replace(/[\s-]+/g, '_');
  return ['router', 'mikrotik_router', 'routeros', 'gateway'].includes(type) || Boolean(device?.router_identity || device?.identity_name);
}

function isOnline(r){if(r.last_seen_at){const t=new Date(r.last_seen_at).getTime();if(Number.isFinite(t)&&Date.now()-t<120000)return true;}return String(r.status||'').toLowerCase()==='online';}

export default function Monitoring(){
 const {tenantId}=useTenant(); const[devices,setDevices]=useState([]);const[sites,setSites]=useState([]);const[sessions,setSessions]=useState([]);const[jobs,setJobs]=useState([]);const[siteId,setSiteId]=useState('all');const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 async function load(){if(!tenantId)return;try{setLoading(true);setError('');const[d,s,a,j]=await Promise.all([getDevices(tenantId),getSites(tenantId),getActiveSessions(tenantId),getProvisioningJobs(tenantId)]);setDevices(d||[]);setSites(s||[]);setSessions(a||[]);setJobs(j||[]);}catch(e){console.error(e);setError(e?.message||'Could not load monitoring data.');}finally{setLoading(false);}}
 useEffect(()=>{load();const t=window.setInterval(load,30000);return()=>window.clearInterval(t);},[tenantId]);
 const routers=useMemo(()=>devices.filter(d=>isRouterDevice(d)&&(siteId==='all'||d.site_id===siteId)),[devices,siteId]);
 const active=useMemo(()=>sessions.filter(s=>String(s.status).toLowerCase()==='online'&&(siteId==='all'||s.site_id===siteId)),[sessions,siteId]);
 const online=routers.filter(isOnline); const failed=jobs.filter(j=>String(j.status).toLowerCase()==='failed'&&(siteId==='all'||j.site_id===siteId));
 const lastPoll=routers.map(r=>r.last_seen_at).filter(Boolean).sort().at(-1);
 return <div className="space-y-6"><PageHeader eyebrow="Network" title="Network Monitoring" description="Router online/offline state, last poll, provisioning failures, CPU, memory, uptime, WAN and live hotspot users by site." actions={<button onClick={load} disabled={loading} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white"><FiRefreshCw className={loading?'animate-spin':''}/>Refresh</button>}/>{error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
 <section className="rounded-3xl border border-blue-100 bg-white p-5 shadow-sm"><label className="text-sm font-semibold">Site<select value={siteId} onChange={e=>setSiteId(e.target.value)} className="mt-2 w-full max-w-md rounded-xl border border-slate-300 bg-white p-3"><option value="all">All sites</option>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></section>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Routers online" value={`${online.length}/${routers.length}`}/><StatCard label="Last router poll" value={lastContact(lastPoll)}/><StatCard label="Failed jobs" value={failed.length}/><StatCard label="Active sessions" value={active.length}/><StatCard label="WAN online" value={routers.filter(r=>String(r.wan_status).toLowerCase()==='online').length}/></div>
 <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-200"><thead className="bg-gradient-to-r from-blue-50 to-cyan-50"><tr>{['Router','Site','Status','Last poll','CPU','Memory','Uptime','Hotspot users','WAN','Last error'].map(h=><th key={h} className="px-4 py-3 text-left text-xs font-bold uppercase tracking-wide text-slate-600">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{loading?<tr><td colSpan={10} className="p-12 text-center text-slate-500">Loading monitoring data…</td></tr>:routers.length===0?<tr><td colSpan={10} className="p-12 text-center text-slate-500">No routers found for this site.</td></tr>:routers.map(r=><tr key={r.id} className="hover:bg-blue-50/30"><td className="px-4 py-4 font-bold">{r.name}</td><td className="px-4 py-4"><SiteBadge siteId={r.site_id} sites={sites}/></td><td className="px-4 py-4"><StatusBadge value={isOnline(r)?'online':'offline'}/></td><td className="px-4 py-4 text-sm"><span className="inline-flex items-center gap-2"><FiClock/>{lastContact(r.last_seen_at)}</span></td><td className="px-4 py-4 text-sm"><FiCpu className="mr-1 inline"/>{r.cpu_usage_percent==null?'—':`${Number(r.cpu_usage_percent).toFixed(0)}%`}</td><td className="px-4 py-4 text-sm"><FiHardDrive className="mr-1 inline"/>{r.memory_usage_percent==null?'—':`${Number(r.memory_usage_percent).toFixed(0)}%`}</td><td className="px-4 py-4 text-sm">{r.uptime_text||formatUptime(r.uptime_seconds)}</td><td className="px-4 py-4 text-sm"><FiUsers className="mr-1 inline"/>{Number(r.active_hotspot_users||0)}</td><td className="px-4 py-4"><span className="inline-flex items-center gap-2"><FiWifi/>{r.wan_status||'—'}</span></td><td className="px-4 py-4 text-sm text-rose-600">{r.last_error||'—'}</td></tr>)}</tbody></table></div></section>
 {failed.length>0&&<section className="rounded-3xl border border-amber-200 bg-amber-50 p-5"><div className="flex items-center gap-2 font-bold text-amber-900"><FiAlertTriangle/>Recent failed provisioning jobs</div><div className="mt-3 space-y-2 text-sm text-amber-800">{failed.slice(0,10).map(j=><div key={j.id}>{j.username||j.id}: {j.failure_reason||'Provisioning failed'}</div>)}</div></section>}
 </div>;
}
