import { useEffect, useMemo, useState } from 'react';
import { FiActivity, FiAlertTriangle, FiClock, FiCpu, FiHardDrive, FiRefreshCw, FiUsers, FiWifi } from 'react-icons/fi';
import { useTenant } from '../../hooks/useTenant';
import { getDevices, getSites, getTableRows } from '../../services/operationsService';
import { PageHeader, SiteBadge, StatCard, StatusBadge } from '../../components/operations/OperationsUI';

function formatUptime(seconds){const n=Number(seconds||0);if(!n)return '—';const d=Math.floor(n/86400),h=Math.floor((n%86400)/3600),m=Math.floor((n%3600)/60);return [d?`${d}d`:null,h?`${h}h`:null,`${m}m`].filter(Boolean).join(' ');}
function lastContact(value){if(!value)return 'Never';const d=new Date(value);if(Number.isNaN(d.getTime()))return 'Never';const diff=Math.max(0,Date.now()-d.getTime());const min=Math.floor(diff/60000);if(min<1)return 'Just now';if(min<60)return `${min} min ago`;const hr=Math.floor(min/60);if(hr<24)return `${hr} hr ago`;return d.toLocaleString();}
function isOnline(router){if(router.last_seen_at){const seen=new Date(router.last_seen_at).getTime();return Number.isFinite(seen)&&Date.now()-seen<120000;}return String(router.status).toLowerCase()==='online';}

export default function Monitoring(){
 const {tenantId}=useTenant(); const [devices,setDevices]=useState([]);const[sites,setSites]=useState([]);const[sessions,setSessions]=useState([]);const[jobs,setJobs]=useState([]);const[siteId,setSiteId]=useState('all');const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 async function load(){if(!tenantId)return;setLoading(true);setError('');const r=await Promise.allSettled([getDevices(tenantId),getSites(tenantId),getTableRows('hotspot_sessions',tenantId),getTableRows('router_provisioning_jobs',tenantId)]);setDevices(r[0].status==='fulfilled'?r[0].value:[]);setSites(r[1].status==='fulfilled'?r[1].value:[]);setSessions(r[2].status==='fulfilled'?r[2].value:[]);setJobs(r[3].status==='fulfilled'?r[3].value:[]);if(r.some(x=>x.status==='rejected'))setError('Some monitoring sources are not yet available. Apply the latest operations SQL; live router metrics will start after the updated RouterOS script checks in.');setLoading(false);}
 useEffect(()=>{load();const timer=setInterval(load,30000);return()=>clearInterval(timer);},[tenantId]);
 const routers=useMemo(()=>devices.filter(d=>d.device_type==='router'&&(siteId==='all'||d.site_id===siteId)),[devices,siteId]);
 const activeSessions=useMemo(()=>sessions.filter(s=>(siteId==='all'||s.site_id===siteId)&&['active','online'].includes(String(s.status).toLowerCase())),[sessions,siteId]);
 const selectedRouterIds=useMemo(()=>new Set(routers.map(r=>r.id)),[routers]);
 const failedJobs=useMemo(()=>jobs.filter(j=>(siteId==='all'||selectedRouterIds.has(j.router_id))&&['failed','error'].includes(String(j.status).toLowerCase())),[jobs,siteId,selectedRouterIds]);
 const online=routers.filter(isOnline).length;
 const recentErrors=useMemo(()=>[
   ...routers.filter(r=>r.last_error).map(r=>({time:r.last_seen_at||r.updated_at,source:r.name,message:r.last_error})),
   ...failedJobs.map(j=>({time:j.updated_at||j.completed_at||j.created_at,source:j.router_name||'Provisioning',message:j.failure_reason||j.last_error||`Provisioning job ${j.id} failed`})),
 ].sort((a,b)=>new Date(b.time||0)-new Date(a.time||0)).slice(0,10),[routers,failedJobs]);

 return <div className="space-y-6"><PageHeader eyebrow="Network operations" title="Network Monitoring" description="Live router health grouped by site: online state, poll time, CPU, memory, uptime, WAN, active users, provisioning failures and recent errors." actions={<button onClick={load} disabled={loading} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white"><FiRefreshCw className={loading?'animate-spin':''}/>Refresh</button>}/>
 {error&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">{error}</div>}
 <section className="rounded-3xl border border-blue-100 bg-white p-5 shadow-sm"><label className="text-sm font-semibold text-slate-700">Monitor site<select value={siteId} onChange={e=>setSiteId(e.target.value)} className="ml-3 rounded-xl border border-slate-300 bg-white px-4 py-2"><option value="all">All sites</option>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></section>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><StatCard label="Routers online" value={`${online}/${routers.length}`} hint="Seen within ~2 minutes"/><StatCard label="Active hotspot users" value={activeSessions.length}/><StatCard label="Failed provisioning" value={failedJobs.length}/><StatCard label="WAN online" value={routers.filter(r=>String(r.wan_status).toLowerCase()==='online').length}/><StatCard label="Recent errors" value={recentErrors.length}/></div>
 <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-200"><thead className="bg-gradient-to-r from-blue-50 to-cyan-50"><tr>{['Router','Site','Status','Last poll','CPU','Memory','Uptime','Hotspot users','WAN'].map(h=><th key={h} className="px-4 py-3 text-left text-xs font-bold uppercase tracking-wide text-slate-600">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{loading?<tr><td colSpan="9" className="p-12 text-center text-slate-500">Loading monitoring data…</td></tr>:routers.length===0?<tr><td colSpan="9" className="p-12 text-center text-slate-500">No routers registered for the selected site.</td></tr>:routers.map(r=>{const onlineNow=isOnline(r);return <tr key={r.id} className="hover:bg-blue-50/30"><td className="px-4 py-4"><div className="font-bold text-slate-900">{r.name}</div><div className="text-xs text-slate-400">{r.router_identity||r.ip_address||'No identity reported'}</div></td><td className="px-4 py-4"><SiteBadge siteId={r.site_id} sites={sites}/></td><td className="px-4 py-4"><StatusBadge value={onlineNow?'online':'offline'}/></td><td className="px-4 py-4 text-sm"><div className="flex items-center gap-1"><FiClock className="text-slate-400"/>{lastContact(r.last_seen_at)}</div></td><td className="px-4 py-4 text-sm"><div className="flex items-center gap-1"><FiCpu className="text-blue-500"/>{r.cpu_usage_percent==null?'—':`${Number(r.cpu_usage_percent).toFixed(0)}%`}</div></td><td className="px-4 py-4 text-sm"><div className="flex items-center gap-1"><FiHardDrive className="text-violet-500"/>{r.memory_usage_percent==null?'—':`${Number(r.memory_usage_percent).toFixed(0)}%`}</div></td><td className="px-4 py-4 text-sm">{r.uptime_text||formatUptime(r.uptime_seconds)}</td><td className="px-4 py-4 text-sm"><div className="flex items-center gap-1"><FiUsers className="text-cyan-600"/>{r.active_hotspot_users??sessions.filter(s=>s.router_id===r.id&&['active','online'].includes(String(s.status).toLowerCase())).length}</div></td><td className="px-4 py-4"><span className="inline-flex items-center gap-2"><FiWifi className={String(r.wan_status).toLowerCase()==='online'?'text-emerald-600':'text-slate-400'}/><StatusBadge value={r.wan_status||'unknown'}/></span></td></tr>})}</tbody></table></div></section>
 <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-4 flex items-center gap-3"><span className="rounded-xl bg-rose-100 p-2 text-rose-700"><FiAlertTriangle/></span><div><h2 className="text-lg font-bold">Recent errors</h2><p className="text-sm text-slate-500">Router-reported errors and failed provisioning jobs.</p></div></div>{recentErrors.length===0?<div className="rounded-2xl bg-emerald-50 p-5 text-sm text-emerald-700">No recent errors are recorded for the selected site.</div>:<div className="divide-y divide-slate-100">{recentErrors.map((x,i)=><div key={i} className="py-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold text-slate-900">{x.source}</p><span className="text-xs text-slate-400">{x.time?new Date(x.time).toLocaleString():'Unknown time'}</span></div><p className="mt-1 text-sm text-rose-700">{x.message}</p></div>)}</div>}</section>
 </div>;
}
