import { useEffect, useMemo, useState } from 'react';
import { FiRefreshCw, FiSearch, FiUsers } from 'react-icons/fi';
import { useTenant } from '../../hooks/useTenant';
import { getDevices, getSites, getTableRows } from '../../services/operationsService';
import { PageHeader, SiteBadge, StatCard } from '../../components/operations/OperationsUI';
import { createSiteResolver, customerKey, isPaid, orderAmount } from '../../utils/operationsData';

export default function Customers(){
  const {tenantId}=useTenant(); const [customerRows,setCustomerRows]=useState([]); const [orders,setOrders]=useState([]); const [devices,setDevices]=useState([]); const [sites,setSites]=useState([]);
  const [siteId,setSiteId]=useState('all'); const [search,setSearch]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  async function load(){if(!tenantId)return;setLoading(true);setError('');const r=await Promise.allSettled([getTableRows('hotspot_customers',tenantId),getTableRows('hotspot_orders',tenantId),getDevices(tenantId),getSites(tenantId)]);setCustomerRows(r[0].status==='fulfilled'?r[0].value:[]);setOrders(r[1].status==='fulfilled'?r[1].value:[]);setDevices(r[2].status==='fulfilled'?r[2].value:[]);setSites(r[3].status==='fulfilled'?r[3].value:[]);if(r[1].status==='rejected')setError('Orders could not be loaded, so purchase totals may be incomplete.');setLoading(false)}
  useEffect(()=>{load()},[tenantId]);
  const resolveSite=useMemo(()=>createSiteResolver(devices),[devices]);
  const customers=useMemo(()=>{
    const map=new Map();
    for(const c of customerRows){const k=customerKey(c)||`id:${c.id}`;map.set(k,{id:c.id,key:k,name:c.name||c.customer_name||'Customer',phone:c.phone||c.customer_phone||'',email:c.email||c.customer_email||'',mac:c.mac_address||'',site_id:c.site_id||null,purchases:Number(c.total_purchases||0),spent:Number(c.total_spent||0),last_seen:c.last_seen_at||c.updated_at||c.created_at,status:c.status||'active'});}
    for(const o of orders){const k=customerKey(o)||`order:${o.id}`;const existing=map.get(k)||{id:k,key:k,name:o.customer_name||'Customer',phone:o.customer_phone||'',email:o.customer_email||'',mac:o.customer_mac_address||'',site_id:resolveSite(o),purchases:0,spent:0,last_seen:null,status:'active'};existing.name=existing.name||o.customer_name||'Customer';existing.phone=existing.phone||o.customer_phone||'';existing.email=existing.email||o.customer_email||'';existing.mac=existing.mac||o.customer_mac_address||'';existing.site_id=existing.site_id||resolveSite(o);existing.purchases+=isPaid(o)?1:0;existing.spent+=isPaid(o)?orderAmount(o):0;const d=o.paid_at||o.created_at;if(d&&(!existing.last_seen||new Date(d)>new Date(existing.last_seen)))existing.last_seen=d;map.set(k,existing);}
    return [...map.values()].sort((a,b)=>new Date(b.last_seen||0)-new Date(a.last_seen||0));
  },[customerRows,orders,resolveSite]);
  const filtered=customers.filter(c=>(siteId==='all'||c.site_id===siteId)&&(!search||[c.name,c.phone,c.email,c.mac].join(' ').toLowerCase().includes(search.toLowerCase())));
  const totalSpent=filtered.reduce((a,c)=>a+c.spent,0); const buyers=filtered.filter(c=>c.purchases>0).length;
  return <div className="space-y-6"><PageHeader eyebrow="Hotspot business" title="Customers" description="Customer and payer activity derived from both the customer register and real hotspot orders, grouped by network site." actions={<button onClick={load} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white"><FiRefreshCw/>Refresh</button>}/>{error&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">{error}</div>}
  <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Customers" value={filtered.length}/><StatCard label="Paying customers" value={buyers}/><StatCard label="Paid purchases" value={filtered.reduce((a,c)=>a+c.purchases,0)}/><StatCard label="Customer revenue" value={`GHS ${totalSpent.toFixed(2)}`}/></div>
  <section className="rounded-3xl border border-blue-100 bg-white p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-2"><div className="relative"><FiSearch className="absolute left-3 top-3 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, phone, email or MAC" className="w-full rounded-xl border border-slate-300 py-2.5 pl-10 pr-4"/></div><select value={siteId} onChange={e=>setSiteId(e.target.value)} className="rounded-xl border border-slate-300 bg-white px-4 py-2.5"><option value="all">All sites</option>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div></section>
  <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-200"><thead className="bg-gradient-to-r from-blue-50 to-cyan-50"><tr>{['Customer','Phone / email','Site','Purchases','Total spent','Last activity'].map(h=><th key={h} className="px-5 py-3 text-left text-xs font-bold uppercase tracking-wide text-slate-600">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{loading?<tr><td colSpan="6" className="p-12 text-center text-slate-500">Loading customers…</td></tr>:filtered.length===0?<tr><td colSpan="6" className="p-12 text-center text-slate-500"><FiUsers className="mx-auto mb-3 text-2xl"/>No customers match the selected site.</td></tr>:filtered.map(c=><tr key={c.key} className="hover:bg-blue-50/30"><td className="px-5 py-4"><div className="font-bold text-slate-900">{c.name}</div><div className="text-xs text-slate-400">{c.mac||'No MAC recorded'}</div></td><td className="px-5 py-4 text-sm"><div>{c.phone||'—'}</div><div className="text-xs text-slate-400">{c.email||'—'}</div></td><td className="px-5 py-4"><SiteBadge siteId={c.site_id} sites={sites}/></td><td className="px-5 py-4 font-semibold">{c.purchases}</td><td className="px-5 py-4 font-bold text-emerald-700">GHS {c.spent.toFixed(2)}</td><td className="px-5 py-4 text-sm">{c.last_seen?new Date(c.last_seen).toLocaleString():'—'}</td></tr>)}</tbody></table></div></section></div>
}
