import { useEffect, useMemo, useState } from 'react';
import { FiRefreshCw, FiSearch, FiShoppingCart } from 'react-icons/fi';
import { useTenant } from '../../hooks/useTenant';
import { getDevices, getSites, getTableRows } from '../../services/operationsService';
import { PageHeader, SiteBadge, StatCard, StatusBadge } from '../../components/operations/OperationsUI';
import { createSiteResolver, isPaid, norm, orderAmount } from '../../utils/operationsData';

export default function Orders(){
 const {tenantId}=useTenant(); const[orders,setOrders]=useState([]);const[transactions,setTransactions]=useState([]);const[devices,setDevices]=useState([]);const[sites,setSites]=useState([]);const[siteId,setSiteId]=useState('all');const[status,setStatus]=useState('all');const[search,setSearch]=useState('');const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 async function load(){if(!tenantId)return;setLoading(true);setError('');const r=await Promise.allSettled([getTableRows('hotspot_orders',tenantId),getTableRows('hotspot_payment_transactions',tenantId),getDevices(tenantId),getSites(tenantId)]);setOrders(r[0].status==='fulfilled'?r[0].value:[]);setTransactions(r[1].status==='fulfilled'?r[1].value:[]);setDevices(r[2].status==='fulfilled'?r[2].value:[]);setSites(r[3].status==='fulfilled'?r[3].value:[]);if(r[0].status==='rejected')setError('Orders could not be loaded.');setLoading(false)} useEffect(()=>{load()},[tenantId]);
 const resolveSite=useMemo(()=>createSiteResolver(devices),[devices]); const txByOrder=useMemo(()=>new Map(transactions.map(t=>[t.order_id,t])),[transactions]);
 const rows=useMemo(()=>orders.map(o=>{const tx=txByOrder.get(o.id);return{...o,resolved_site_id:resolveSite(o),display_reference:o.payment_reference||tx?.provider_reference||tx?.internal_reference||'—',display_payment_status:o.payment_status||tx?.status||'pending',display_amount:orderAmount(o)}}),[orders,txByOrder,resolveSite]);
 const filtered=rows.filter(o=>(siteId==='all'||o.resolved_site_id===siteId)&&(status==='all'||norm(o.display_payment_status)===status)&&(!search||[o.customer_name,o.customer_phone,o.plan_name,o.order_number,o.display_reference].filter(Boolean).join(' ').toLowerCase().includes(search.toLowerCase())));
 const paid=filtered.filter(isPaid); const revenue=paid.reduce((a,o)=>a+o.display_amount,0); const pendingProvision=filtered.filter(o=>['pending','processing','queued'].includes(norm(o.provisioning_status))).length;
 return <div className="space-y-6"><PageHeader eyebrow="Hotspot business" title="Orders & Payments" description="Track real online purchases, Paystack references, payment state and router provisioning by site." actions={<button onClick={load} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white"><FiRefreshCw/>Refresh</button>}/>{error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Orders" value={filtered.length}/><StatCard label="Paid" value={paid.length}/><StatCard label="Revenue" value={`GHS ${revenue.toFixed(2)}`}/><StatCard label="Pending provisioning" value={pendingProvision}/></div>
 <section className="rounded-3xl border border-blue-100 bg-white p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-3"><div className="relative"><FiSearch className="absolute left-3 top-3 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer, plan, order or reference" className="w-full rounded-xl border border-slate-300 py-2.5 pl-10 pr-4"/></div><select value={siteId} onChange={e=>setSiteId(e.target.value)} className="rounded-xl border border-slate-300 bg-white px-4 py-2.5"><option value="all">All sites</option>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-slate-300 bg-white px-4 py-2.5"><option value="all">All payment statuses</option><option value="paid">Paid</option><option value="pending">Pending</option><option value="failed">Failed</option><option value="initialized">Initialized</option></select></div></section>
 <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-200"><thead className="bg-gradient-to-r from-blue-50 to-cyan-50"><tr>{['Customer','Plan','Site','Amount','Payment','Provisioning','Reference','Created'].map(h=><th key={h} className="px-4 py-3 text-left text-xs font-bold uppercase tracking-wide text-slate-600">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{loading?<tr><td colSpan="8" className="p-12 text-center text-slate-500">Loading orders…</td></tr>:filtered.length===0?<tr><td colSpan="8" className="p-12 text-center text-slate-500"><FiShoppingCart className="mx-auto mb-3 text-2xl"/>No orders match the selected filters.</td></tr>:filtered.map(o=><tr key={o.id} className="hover:bg-blue-50/30"><td className="px-4 py-4"><div className="font-bold text-slate-900">{o.customer_name||'Customer'}</div><div className="text-xs text-slate-400">{o.customer_phone||'—'}</div></td><td className="px-4 py-4 text-sm">{o.plan_name||o.plan_code||'—'}</td><td className="px-4 py-4"><SiteBadge siteId={o.resolved_site_id} sites={sites}/></td><td className="px-4 py-4 font-bold text-emerald-700">{o.currency_code||'GHS'} {o.display_amount.toFixed(2)}</td><td className="px-4 py-4"><StatusBadge value={o.display_payment_status}/></td><td className="px-4 py-4"><StatusBadge value={o.provisioning_status||'not_started'}/></td><td className="px-4 py-4 text-xs font-mono text-slate-600">{o.display_reference}</td><td className="px-4 py-4 text-sm">{o.created_at?new Date(o.created_at).toLocaleString():'—'}</td></tr>)}</tbody></table></div></section></div>
}
