import { useEffect, useMemo, useState } from 'react';
import { FiMessageSquare, FiPlus, FiPrinter, FiShare2, FiShoppingBag } from 'react-icons/fi';
import { useTenant } from '../../hooks/useTenant';
import { generateVouchers, getDevices, getPlans, getSites, getVouchers, markVoucherSold } from '../../services/operationsService';
import { EmptyRow, Modal, PageHeader, SiteBadge, StatCard, StatusBadge, Toolbar } from '../../components/operations/OperationsUI';

export default function Vouchers(){
 const {tenantId}=useTenant(); const [rows,setRows]=useState([]); const [sites,setSites]=useState([]); const [plans,setPlans]=useState([]); const [devices,setDevices]=useState([]);
 const [search,setSearch]=useState(''); const [siteId,setSiteId]=useState('all'); const [status,setStatus]=useState('all'); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [generated,setGenerated]=useState([]); const [form,setForm]=useState({plan_id:'',site_id:'',router_id:'',quantity:10,mode:'manual',vendor_name:''});
 async function load(){if(!tenantId)return;try{setLoading(true);setError('');const [v,s,p,d]=await Promise.all([getVouchers(tenantId),getSites(tenantId),getPlans(tenantId),getDevices(tenantId)]);setRows(v);setSites(s);setPlans(p);setDevices(d);}catch(e){setError(e.message||'Could not load vouchers.');}finally{setLoading(false)}} useEffect(()=>{load()},[tenantId]);
 const filtered=useMemo(()=>rows.filter(r=>{const h=[r.username,r.password,r.plan_name,r.vendor_name,r.customer_phone].filter(Boolean).join(' ').toLowerCase();return(!search||h.includes(search.toLowerCase()))&&(siteId==='all'||r.site_id===siteId)&&(status==='all'||r.status===status)}),[rows,search,siteId,status]);
 async function submit(e){e.preventDefault();const plan=plans.find(p=>p.id===form.plan_id);if(!plan){setError('Select an internet plan.');return}const qty=Math.max(1,Math.min(500,Number(form.quantity)||1));try{setSaving(true);setError('');const data=await generateVouchers({tenantId,siteId:form.site_id,routerId:form.router_id,plan,quantity:qty,mode:form.mode,vendorName:form.vendor_name});setGenerated(data);setOpen(false);await load()}catch(e2){setError(`${e2.message||'Could not generate vouchers.'} Run the included SQL migration if voucher columns are missing.`)}finally{setSaving(false)}}
 function textFor(v){return `CloudRouter Internet Voucher\nPlan: ${v.plan_name||''}\nUsername: ${v.username}\nPassword: ${v.password}\nPrice: ${v.currency_code||'GHS'} ${v.price||''}`}
 function printVouchers(list){const html=list.map(v=>`<div style="border:1px dashed #111;padding:18px;margin:10px;width:280px;display:inline-block;font-family:Arial"><h3>CloudRouter WiFi</h3><b>${v.plan_name||'Internet Voucher'}</b><p>Username: <strong>${v.username}</strong><br/>Password: <strong>${v.password}</strong><br/>Price: ${v.currency_code||'GHS'} ${v.price||''}</p></div>`).join('');const w=window.open('','_blank');w.document.write(`<html><body>${html}</body></html>`);w.document.close();w.print()}
 async function share(v){const text=textFor(v);if(navigator.share)await navigator.share({title:'CloudRouter voucher',text});else await navigator.clipboard.writeText(text)}
 async function sell(v){const phone=window.prompt('Customer phone number (optional):','');try{await markVoucherSold(v.id,tenantId,{phone});await load()}catch(e){setError(e.message)}}
 return <div className="space-y-6"><PageHeader eyebrow="Hotspot business" title="Vouchers" description="Generate vouchers manually or in batches from active plans, assign them to sites and vendors, print them, share them by phone, or send them through SMS." actions={<button onClick={()=>{setForm({plan_id:plans[0]?.id||'',site_id:sites[0]?.id||'',router_id:'',quantity:10,mode:'manual',vendor_name:''});setOpen(true)}} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white"><FiPlus/>Generate vouchers</button>}/>
 {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Total vouchers" value={rows.length}/><StatCard label="Available" value={rows.filter(r=>r.status==='available').length}/><StatCard label="Sold" value={rows.filter(r=>r.status==='sold').length}/><StatCard label="Active / used" value={rows.filter(r=>['active','used'].includes(r.status)).length}/></div>
 <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><Toolbar search={search} onSearch={setSearch} siteId={siteId} onSiteChange={setSiteId} sites={sites} status={status} onStatusChange={setStatus} statuses={[...new Set(rows.map(r=>r.status).filter(Boolean))]} loading={loading} onRefresh={load}/><div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-200"><thead className="bg-slate-50"><tr>{['Voucher','Plan','Site','Vendor','Status','Price','Actions'].map(h=><th key={h} className="px-5 py-3 text-left text-xs font-semibold uppercase text-slate-500">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{loading?<EmptyRow colSpan={7} text="Loading vouchers…"/>:filtered.length===0?<EmptyRow colSpan={7} text="No vouchers match this site or status."/>:filtered.map(v=><tr key={v.id}><td className="px-5 py-4"><div className="font-semibold text-slate-900">{v.username}</div><div className="text-xs text-slate-400">{v.password}</div></td><td className="px-5 py-4 text-sm">{v.plan_name||'—'}</td><td className="px-5 py-4"><SiteBadge siteId={v.site_id} sites={sites}/></td><td className="px-5 py-4 text-sm">{v.vendor_name||'Direct sale'}</td><td className="px-5 py-4"><StatusBadge value={v.status}/></td><td className="px-5 py-4 text-sm">{v.currency_code||'GHS'} {Number(v.price||0).toFixed(2)}</td><td className="px-5 py-4"><div className="flex gap-2"><button title="Print" onClick={()=>printVouchers([v])} className="rounded-lg border p-2"><FiPrinter/></button><button title="Share" onClick={()=>share(v)} className="rounded-lg border p-2"><FiShare2/></button><a title="SMS" href={`sms:${v.customer_phone||''}?body=${encodeURIComponent(textFor(v))}`} className="rounded-lg border p-2"><FiMessageSquare/></a>{v.status==='available'&&<button title="Mark sold" onClick={()=>sell(v)} className="rounded-lg border p-2"><FiShoppingBag/></button>}</div></td></tr>)}</tbody></table></div></section>
 <Modal open={open} title="Generate vouchers" onClose={()=>setOpen(false)}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Plan<select value={form.plan_id} onChange={e=>setForm(x=>({...x,plan_id:e.target.value}))} className="mt-2 w-full rounded-xl border p-3"><option value="">Select plan</option>{plans.filter(p=>p.is_active!==false).map(p=><option key={p.id} value={p.id}>{p.name} — {p.currency_code||'GHS'} {p.price}</option>)}</select></label><label className="text-sm font-semibold">Site<select value={form.site_id} onChange={e=>setForm(x=>({...x,site_id:e.target.value,router_id:''}))} className="mt-2 w-full rounded-xl border p-3"><option value="">Unassigned</option>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="text-sm font-semibold">Router<select value={form.router_id} onChange={e=>setForm(x=>({...x,router_id:e.target.value}))} className="mt-2 w-full rounded-xl border p-3"><option value="">Any router at site</option>{devices.filter(d=>d.device_type==='router'&&(!form.site_id||d.site_id===form.site_id)).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className="text-sm font-semibold">Quantity<input type="number" min="1" max="500" value={form.quantity} onChange={e=>setForm(x=>({...x,quantity:e.target.value}))} className="mt-2 w-full rounded-xl border p-3"/></label><label className="text-sm font-semibold">Generation mode<select value={form.mode} onChange={e=>setForm(x=>({...x,mode:e.target.value}))} className="mt-2 w-full rounded-xl border p-3"><option value="manual">Manual batch</option><option value="automatic">Automatic stock batch</option></select></label><label className="text-sm font-semibold">Vendor / agent<input value={form.vendor_name} onChange={e=>setForm(x=>({...x,vendor_name:e.target.value}))} className="mt-2 w-full rounded-xl border p-3" placeholder="Optional vendor name"/></label><div className="sm:col-span-2 flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border px-4 py-3 font-semibold">Cancel</button><button disabled={saving} className="rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white">{saving?'Generating…':'Generate batch'}</button></div></form></Modal>
 <Modal open={generated.length>0} title={`${generated.length} vouchers generated`} onClose={()=>setGenerated([])} wide><div className="mb-4 flex justify-end"><button onClick={()=>printVouchers(generated)} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white"><FiPrinter/>Print batch</button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{generated.map(v=><div key={v.id} className="rounded-2xl border border-dashed border-slate-400 p-4"><p className="font-bold">{v.plan_name}</p><p className="mt-3 text-sm">Username: <b>{v.username}</b><br/>Password: <b>{v.password}</b></p></div>)}</div></Modal>
 </div>
}
