import { useEffect, useMemo, useState } from 'react';
import { FiActivity, FiCalendar, FiTrendingUp } from 'react-icons/fi';
import { useTenant } from '../../hooks/useTenant';
import { getDevices, getSites, getTableRows } from '../../services/operationsService';
import { PageHeader, StatCard } from '../../components/operations/OperationsUI';
import { money, periodRange, toInputDate, withinRange } from '../../utils/reporting';
import { ACTIVE_SESSION_STATUSES, createSiteResolver, customerKey, isPaid, norm, orderAmount } from '../../utils/operationsData';

function Bars({items,format=v=>v}){const max=Math.max(1,...items.map(x=>Number(x.value||0)));return <div className="space-y-3">{items.length===0?<p className="py-8 text-center text-sm text-slate-500">No data for this period.</p>:items.map((x,i)=><div key={`${x.label}-${i}`}><div className="mb-1 flex justify-between gap-3 text-sm"><span className="truncate font-medium text-slate-700">{x.label}</span><strong>{format(x.value)}</strong></div><div className="h-2.5 rounded-full bg-slate-100"><div className="h-2.5 rounded-full bg-gradient-to-r from-blue-600 to-cyan-400" style={{width:`${Math.max(4,(Number(x.value||0)/max)*100)}%`}}/></div></div>)}</div>}
function dayKey(v){const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,10)}
export default function Analytics(){
 const {tenantId}=useTenant();const[sites,setSites]=useState([]);const[devices,setDevices]=useState([]);const[orders,setOrders]=useState([]);const[sessions,setSessions]=useState([]);const[vouchers,setVouchers]=useState([]);const[siteId,setSiteId]=useState('all');const[period,setPeriod]=useState('this_month');const[fromDate,setFromDate]=useState(toInputDate(new Date()));const[toDate,setToDate]=useState(toInputDate(new Date()));const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 async function load(){if(!tenantId)return;setLoading(true);setError('');const r=await Promise.allSettled([getSites(tenantId),getDevices(tenantId),getTableRows('hotspot_orders',tenantId),getTableRows('hotspot_sessions',tenantId),getTableRows('hotspot_vouchers',tenantId)]);setSites(r[0].status==='fulfilled'?r[0].value:[]);setDevices(r[1].status==='fulfilled'?r[1].value:[]);setOrders(r[2].status==='fulfilled'?r[2].value:[]);setSessions(r[3].status==='fulfilled'?r[3].value:[]);setVouchers(r[4].status==='fulfilled'?r[4].value:[]);if(r.some(x=>x.status==='rejected'))setError('Some analytics sources are unavailable. Available metrics are still shown.');setLoading(false)}useEffect(()=>{load()},[tenantId]);
 const range=useMemo(()=>periodRange(period,fromDate,toDate),[period,fromDate,toDate]);const resolveSite=useMemo(()=>createSiteResolver(devices),[devices]);
 const os=useMemo(()=>orders.map(x=>({...x,resolved_site_id:resolveSite(x)})).filter(x=>(siteId==='all'||x.resolved_site_id===siteId)&&withinRange(x,range,['paid_at','created_at'])),[orders,resolveSite,siteId,range]);
 const ss=useMemo(()=>sessions.map(x=>({...x,resolved_site_id:resolveSite(x)})).filter(x=>(siteId==='all'||x.resolved_site_id===siteId)&&withinRange(x,range,['started_at','created_at'])),[sessions,resolveSite,siteId,range]);
 const paid=os.filter(isPaid),revenue=paid.reduce((a,x)=>a+orderAmount(x),0),customerCount=new Set(paid.map(customerKey).filter(Boolean)).size,arpu=customerCount?revenue/customerCount:0;
 const routers=devices.filter(d=>d.device_type==='router'&&(siteId==='all'||d.site_id===siteId));const onlineRouters=routers.filter(r=>r.last_seen_at&&Date.now()-new Date(r.last_seen_at).getTime()<120000).length;const activeDetailed=ss.filter(s=>ACTIVE_SESSION_STATUSES.has(norm(s.status))).length;const activeRouterTotal=routers.reduce((a,r)=>a+Number(r.active_hotspot_users||0),0);const activeUsers=Math.max(activeDetailed,activeRouterTotal);
 const planRows=useMemo(()=>{const m=new Map();for(const x of paid){const k=x.plan_name||x.plan_code||'Unnamed plan',v=m.get(k)||{label:k,count:0,value:0};v.count++;v.value+=orderAmount(x);m.set(k,v)}return[...m.values()].sort((a,b)=>b.count-a.count).slice(0,8)},[paid]);
 const siteRows=useMemo(()=>sites.filter(s=>siteId==='all'||s.id===siteId).map(s=>({label:s.name,value:paid.filter(x=>x.resolved_site_id===s.id).reduce((a,x)=>a+orderAmount(x),0)})).sort((a,b)=>b.value-a.value),[sites,siteId,paid]);
 const daily=useMemo(()=>{const m=new Map();for(const x of [...paid,...ss]){const key=dayKey(x.paid_at||x.started_at||x.created_at);if(!key)continue;const id=customerKey(x)||x.username||x.mac_address||x.id;if(!m.has(key))m.set(key,new Set());m.get(key).add(id)}return[...m.entries()].map(([label,s])=>({label,value:s.size})).sort((a,b)=>a.label.localeCompare(b.label)).slice(-14)},[paid,ss]);
 const insights=[];if(planRows[0])insights.push(`${planRows[0].label} is the most purchased plan with ${planRows[0].count} paid purchases.`);if(siteRows[0])insights.push(`${siteRows[0].label} is the highest-revenue site for the selected period at ${money(siteRows[0].value)}.`);if(routers.length&&onlineRouters<routers.length)insights.push(`${routers.length-onlineRouters} router(s) are not currently reporting online.`);if(activeRouterTotal>activeDetailed)insights.push('Router heartbeat reports more live users than the detailed session table; deploy the included session-sync router upgrade for per-user analytics.');
 return <div className="space-y-6"><PageHeader eyebrow="Decision support" title="Analytics & Decision Support" description="Business trends, users per day, plan popularity, site performance, ARPU and network health from real CloudRouter records."/>{error&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">{error}</div>}
 <section className="rounded-3xl border border-blue-100 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2 text-sm font-bold text-blue-800"><FiCalendar/>Analytics filters</div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="text-sm font-semibold">Site<select value={siteId} onChange={e=>setSiteId(e.target.value)} className="mt-2 w-full rounded-xl border p-2.5"><option value="all">All sites</option>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="text-sm font-semibold">Period<select value={period} onChange={e=>setPeriod(e.target.value)} className="mt-2 w-full rounded-xl border p-2.5"><option value="today">Today</option><option value="this_week">This week</option><option value="last_7_days">Last 7 days</option><option value="this_month">This month</option><option value="last_month">Last month</option><option value="this_year">This year</option><option value="all">All time</option><option value="custom">Custom</option></select></label><label className="text-sm font-semibold">From<input type="date" disabled={period!=='custom'} value={fromDate} onChange={e=>setFromDate(e.target.value)} className="mt-2 w-full rounded-xl border p-2.5 disabled:bg-slate-100"/></label><label className="text-sm font-semibold">To<input type="date" disabled={period!=='custom'} value={toDate} onChange={e=>setToDate(e.target.value)} className="mt-2 w-full rounded-xl border p-2.5 disabled:bg-slate-100"/></label></div></section>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><StatCard label="Revenue" value={loading?'—':money(revenue)}/><StatCard label="Paid purchases" value={paid.length}/><StatCard label="Paying customers" value={customerCount}/><StatCard label="ARPU" value={money(arpu)}/><StatCard label="Active users" value={activeUsers}/><StatCard label="Routers online" value={`${onlineRouters}/${routers.length}`}/></div>
 <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-5 text-lg font-bold">Most purchased plans</h2><Bars items={planRows.map(x=>({label:`${x.label} (${x.count})`,value:x.value}))} format={money}/></section><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-5 text-lg font-bold">Revenue by site</h2><Bars items={siteRows} format={money}/></section></div>
 <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-5 text-lg font-bold">Users per day</h2><Bars items={daily}/></section><section className="rounded-3xl border border-blue-100 bg-gradient-to-br from-blue-50 to-white p-6 shadow-sm"><div className="mb-4 flex items-center gap-2"><FiTrendingUp className="text-blue-600"/><h2 className="text-lg font-bold">Decision support</h2></div>{insights.length?<ul className="space-y-3 text-sm text-slate-700">{insights.map((x,i)=><li key={i} className="rounded-2xl bg-white p-4 shadow-sm">{x}</li>)}</ul>:<p className="text-sm text-slate-500">More insights will appear as paid orders and session history accumulate.</p>}</section></div>
 </div>
}
