import { FiMapPin, FiRefreshCw, FiSearch } from 'react-icons/fi';

export function PageHeader({ eyebrow = 'CloudRouter', title, description, actions }) {
  return <section className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-blue-600">{eyebrow}</p><h1 className="mt-2 text-3xl font-black text-slate-950">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">{description}</p></div>{actions && <div className="flex flex-wrap gap-2">{actions}</div>}</section>;
}

export function StatCard({ label, value, hint, tone = 'blue' }) {
  const tones={blue:'from-blue-600 to-cyan-500',emerald:'from-emerald-500 to-teal-500',violet:'from-violet-500 to-fuchsia-500',amber:'from-amber-500 to-orange-500',rose:'from-rose-500 to-pink-500'};
  return <div className="overflow-hidden rounded-2xl border border-white bg-white shadow-sm"><div className={`h-1 bg-gradient-to-r ${tones[tone]||tones.blue}`}/><div className="p-5"><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-slate-950">{value}</p>{hint && <p className="mt-1 text-xs text-slate-400">{hint}</p>}</div></div>;
}

export function Toolbar({ search, onSearch, siteId, onSiteChange, sites = [], status, onStatusChange, statuses = [], loading, onRefresh }) {
  return <div className="grid gap-3 border-b border-slate-200 bg-gradient-to-r from-white to-blue-50/50 p-5 lg:grid-cols-[1fr_220px_180px_auto]"><label className="relative"><FiSearch className="absolute left-3 top-3 text-slate-400"/><input value={search} onChange={(e)=>onSearch(e.target.value)} placeholder="Search records" className="w-full rounded-xl border border-slate-300 py-2.5 pl-9 pr-3 text-sm"/></label><label className="relative"><FiMapPin className="absolute left-3 top-3 text-slate-400"/><select value={siteId} onChange={(e)=>onSiteChange(e.target.value)} className="w-full rounded-xl border border-slate-300 bg-white py-2.5 pl-9 pr-3 text-sm"><option value="all">All sites</option>{sites.map((site)=><option key={site.id} value={site.id}>{site.name}</option>)}</select></label>{onStatusChange ? <select value={status} onChange={(e)=>onStatusChange(e.target.value)} className="rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="all">All statuses</option>{statuses.map((item)=><option key={item} value={item}>{String(item).replaceAll('_',' ')}</option>)}</select> : <span/>}<button type="button" onClick={onRefresh} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl border border-blue-100 bg-white px-4 py-2.5 text-sm font-semibold text-blue-700 hover:bg-blue-50"><FiRefreshCw className={loading ? 'animate-spin' : ''}/>Refresh</button></div>;
}

export function SiteBadge({ siteId, sites }) { const site = sites.find((item)=>item.id === siteId); return <span className="inline-flex rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-700">{site?.name || 'Unassigned'}</span>; }
export function StatusBadge({ value }) { const normalized=String(value||'unknown').toLowerCase();const positive=['active','completed','successful','success','paid','online','sold'].includes(normalized);const warning=['pending','available','reserved','pending_installation','processing','unknown'].includes(normalized);const danger=['failed','error','offline','disabled','expired','cancelled'].includes(normalized);const classes=positive?'bg-emerald-50 text-emerald-700':danger?'bg-rose-50 text-rose-700':warning?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-700';return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${classes}`}>{normalized.replaceAll('_',' ')}</span>; }
export function Modal({ open, title, children, onClose, wide = false }) { if (!open) return null; return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/60 p-4"><div className={`max-h-[92vh] w-full overflow-y-auto rounded-3xl bg-white shadow-2xl ${wide ? 'max-w-4xl' : 'max-w-2xl'}`}><div className="flex items-center justify-between border-b border-slate-200 px-6 py-5"><h2 className="text-xl font-bold text-slate-950">{title}</h2><button type="button" onClick={onClose} className="rounded-lg px-3 py-2 text-sm font-semibold text-slate-500 hover:bg-slate-100">Close</button></div><div className="p-6">{children}</div></div></div>; }
export function EmptyRow({ colSpan, text = 'No records found.' }) { return <tr><td colSpan={colSpan} className="px-5 py-14 text-center text-sm text-slate-500">{text}</td></tr>; }
