import { useEffect, useMemo, useState } from 'react';
import { useTenant } from '../../hooks/useTenant';
import { getSites, getTableRows } from '../../services/operationsService';
import { EmptyRow, PageHeader, SiteBadge, StatCard, StatusBadge, Toolbar } from './OperationsUI';

function display(value){if(value===null||value===undefined||value==='')return '—';if(typeof value==='number')return value.toLocaleString();if(typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(value))return new Date(value).toLocaleString();return String(value).replaceAll('_',' ')}
export default function SiteGroupedTable({title,description,table,columns,statusKey='status',summary=[]}){
 const {tenantId}=useTenant();const[rows,setRows]=useState([]);const[sites,setSites]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[search,setSearch]=useState('');const[siteId,setSiteId]=useState('all');const[status,setStatus]=useState('all');
 async function load(){if(!tenantId)return;try{setLoading(true);setError('');const[r,s]=await Promise.all([getTableRows(table,tenantId),getSites(tenantId)]);setRows(r);setSites(s)}catch(e){setError(e.message||`Could not load ${title.toLowerCase()}.`)}finally{setLoading(false)}}useEffect(()=>{load()},[tenantId,table]);
 const filtered=useMemo(()=>rows.filter(row=>{const h=columns.map(c=>row[c.key]).filter(Boolean).join(' ').toLowerCase();return(!search||h.includes(search.toLowerCase()))&&(siteId==='all'||row.site_id===siteId)&&(status==='all'||row[statusKey]===status)}),[rows,columns,search,siteId,status,statusKey]);
 return <div className="space-y-6"><PageHeader title={title} description={description}/>{error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="All sites" value={rows.length}/>{summary.slice(0,3).map(item=><StatCard key={item.label} label={item.label} value={item.value(rows)}/>)}</div><section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><Toolbar search={search} onSearch={setSearch} siteId={siteId} onSiteChange={setSiteId} sites={sites} status={status} onStatusChange={setStatus} statuses={[...new Set(rows.map(r=>r[statusKey]).filter(Boolean))]} loading={loading} onRefresh={load}/><div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-200"><thead className="bg-slate-50"><tr>{columns.map(c=><th key={c.key} className="px-5 py-3 text-left text-xs font-semibold uppercase text-slate-500">{c.label}</th>)}<th className="px-5 py-3 text-left text-xs font-semibold uppercase text-slate-500">Site</th></tr></thead><tbody className="divide-y divide-slate-100">{loading?<EmptyRow colSpan={columns.length+1} text="Loading…"/>:filtered.length===0?<EmptyRow colSpan={columns.length+1}/>:filtered.map(row=><tr key={row.id} className="hover:bg-slate-50">{columns.map(c=><td key={c.key} className="px-5 py-4 text-sm text-slate-700">{c.status?<StatusBadge value={row[c.key]}/>:c.render?c.render(row[c.key],row):display(row[c.key])}</td>)}<td className="px-5 py-4"><SiteBadge siteId={row.site_id} sites={sites}/></td></tr>)}</tbody></table></div></section></div>
}
