import { createClient } from 'npm:@supabase/supabase-js@2';
const corsHeaders={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const json=(body:Record<string,unknown>,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,'Content-Type':'application/json'}});
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(req.method!=='POST')return json({error:'Method not allowed.'},405);
 const url=Deno.env.get('SUPABASE_URL'),anon=Deno.env.get('SUPABASE_ANON_KEY'),service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),auth=req.headers.get('Authorization');if(!url||!anon||!service)return json({error:'Function is not configured.'},500);if(!auth)return json({error:'Authentication is required.'},401);
 const body=await req.json().catch(()=>null);const tenantId=body?.tenantId?.trim(),fullName=body?.fullName?.trim(),email=body?.email?.trim().toLowerCase(),password=body?.password,roleId=body?.roleId?.trim();if(!tenantId||!fullName||!email||!password||!roleId)return json({error:'Tenant, name, email, password and role are required.'},400);if(password.length<8)return json({error:'Password must be at least 8 characters.'},400);
 const caller=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const admin=createClient(url,service,{auth:{persistSession:false}});const{data:userData,error:userError}=await caller.auth.getUser();if(userError||!userData.user)return json({error:'Invalid session.'},401);
 const{data:membership}=await admin.from('tenant_users').select('id,role_id,roles(code)').eq('tenant_id',tenantId).eq('user_id',userData.user.id).eq('status','active').maybeSingle();const code=(membership as any)?.roles?.code;if(!['owner','admin','administrator'].includes(code))return json({error:'Only an Owner or Administrator can create users.'},403);
 const{data:created,error:createError}=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:fullName}});if(createError||!created.user)return json({error:createError?.message||'User account could not be created.'},400);
 const userId=created.user.id;const{error:profileError}=await admin.from('profiles').upsert({id:userId,full_name:fullName,email},{onConflict:'id'});if(profileError){await admin.auth.admin.deleteUser(userId);return json({error:profileError.message},400);}
 const{error:memberError}=await admin.from('tenant_users').insert({tenant_id:tenantId,user_id:userId,role_id:roleId,status:'active'});if(memberError){await admin.auth.admin.deleteUser(userId);return json({error:memberError.message},400);}return json({success:true,userId,email,message:'User created successfully.'});});
