import { Link } from 'react-router-dom';
import { FiActivity, FiArrowRight, FiBarChart2, FiCheck, FiCloud, FiCreditCard, FiMapPin, FiRadio, FiShield, FiUsers, FiWifi, FiZap } from 'react-icons/fi';
import heroBackground from '../../assets/cloudrouter-hero.svg';

const features=[
  [FiWifi,'Hotspot billing','Sell time and data plans through MikroTik hotspots with automated access provisioning.'],
  [FiCreditCard,'Payments & vouchers','Support online payments, manual vouchers, vendors, printing and phone sharing.'],
  [FiActivity,'Network monitoring','See router online/offline state, WAN health, CPU, memory, uptime and hotspot users.'],
  [FiMapPin,'Multi-site operations','Manage multiple hotspot locations under one tenant and compare each site separately.'],
  [FiBarChart2,'Analytics & reports','Track revenue trends, users per day, plan popularity and site performance.'],
  [FiShield,'Tenant isolation','Keep each hotspot operator, staff account, network and customer dataset securely separated.'],
];

function Brand(){return <span className="flex items-center gap-3"><span className="relative flex h-11 w-11 items-center justify-center rounded-2xl bg-white/15 ring-1 ring-white/20"><FiCloud className="text-xl text-white"/><FiWifi className="absolute -bottom-1 -right-1 rounded-full bg-cyan-300 p-1 text-blue-800"/></span><span><strong className="block text-lg text-white">CloudRouter</strong><small className="text-blue-100">Hotspot Cloud Platform</small></span></span>;}

export default function LandingPage(){return <div className="min-h-screen bg-blue-950 text-white">
  <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-blue-950/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6 lg:px-8"><Link to="/"><Brand/></Link><nav className="flex items-center gap-2"><a href="#features" className="hidden rounded-xl px-4 py-2 text-sm font-semibold text-blue-100 hover:bg-white/10 md:inline-flex">Features</a><Link to="/login" className="rounded-xl px-4 py-2 text-sm font-semibold text-white hover:bg-white/10">Sign in</Link><Link to="/register" className="rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-blue-700 shadow-lg">Start free trial</Link></nav></div></header>

  <main>
    <section className="relative isolate overflow-hidden pt-24">
      <img src={heroBackground} alt="Cloud hotspot network illustration" className="absolute inset-0 -z-20 h-full w-full object-cover opacity-55"/>
      <div className="absolute inset-0 -z-10 bg-gradient-to-br from-blue-950/95 via-blue-800/88 to-cyan-600/72"/>
      <div className="mx-auto grid max-w-7xl items-center gap-12 px-4 py-20 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-28">
        <div><span className="inline-flex items-center gap-2 rounded-full border border-cyan-200/30 bg-white/10 px-4 py-2 text-sm font-semibold text-cyan-100"><FiZap/>Built for hotspot and ISP operators</span><h1 className="mt-7 text-4xl font-black leading-[1.05] text-white sm:text-6xl lg:text-7xl">Control your hotspot business <span className="block text-cyan-200">from the cloud.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-blue-100 sm:text-xl">CloudRouter brings MikroTik provisioning, plans, vouchers, payments, customers, monitoring, reports and business analytics into one professional workspace.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to="/register" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-white px-6 py-4 font-bold text-blue-700 shadow-2xl transition hover:-translate-y-0.5">Start 14-day free trial <FiArrowRight/></Link><a href="#features" className="inline-flex items-center justify-center gap-2 rounded-2xl border border-white/25 bg-white/10 px-6 py-4 font-bold text-white backdrop-blur hover:bg-white/15"><FiWifi/>Explore features</a></div><div className="mt-7 flex flex-wrap gap-4 text-sm text-blue-100">{['No credit card required','Multi-site ready','MikroTik focused'].map(x=><span key={x} className="inline-flex items-center gap-2"><FiCheck className="text-cyan-300"/>{x}</span>)}</div></div>
        <div className="relative"><div className="absolute -inset-8 rounded-full bg-cyan-300/20 blur-3xl"/><div className="relative overflow-hidden rounded-[2.2rem] border border-white/20 bg-white/10 p-6 shadow-2xl backdrop-blur-xl"><div className="rounded-3xl border border-white/15 bg-blue-950/35 p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-200">Cloud operations</p><h2 className="mt-2 text-2xl font-black text-white">One workspace. Every site.</h2></div><span className="rounded-2xl bg-emerald-400/15 p-3 text-emerald-200"><FiActivity className="text-2xl"/></span></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{[[FiMapPin,'Sites','Organise routers, customers and revenue by location.'],[FiRadio,'Routers','Register devices and generate tenant-specific scripts.'],[FiUsers,'Customers','Track buyers, sessions and repeat activity.'],[FiBarChart2,'Decision support','Spot trends, popular plans and network risks.']].map(([Icon,title,text])=><div key={title} className="rounded-2xl border border-white/10 bg-white/[0.08] p-4"><Icon className="text-xl text-cyan-200"/><p className="mt-3 font-bold text-white">{title}</p><p className="mt-1 text-xs leading-5 text-blue-100">{text}</p></div>)}</div><div className="mt-4 rounded-2xl border border-cyan-200/20 bg-gradient-to-r from-cyan-300/15 to-blue-300/10 p-4"><div className="flex items-center gap-3"><FiCloud className="text-3xl text-cyan-200"/><div><p className="font-bold text-white">Live data only</p><p className="text-sm text-blue-100">Your dashboard starts clean and fills with your own hotspot activity—no demo revenue or fake customer counts.</p></div></div></div></div></div></div>
      </div>
    </section>

    <section id="features" className="bg-white py-20 text-slate-900"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-blue-600">Purpose-built</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Everything needed to operate and grow a hotspot business</h2><p className="mt-4 text-slate-600">Its language and workflows are designed specifically around sites, routers, internet plans, vouchers, sessions, customers and provisioning.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{features.map(([Icon,title,text])=><article key={title} className="rounded-3xl border border-blue-100 bg-gradient-to-br from-blue-50/80 to-white p-6 shadow-sm"><span className="inline-flex rounded-2xl bg-blue-600 p-3 text-white"><Icon/></span><h3 className="mt-5 text-xl font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>

    <section className="bg-gradient-to-r from-blue-700 to-cyan-500 py-16"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-6 px-4 sm:px-6 lg:flex-row lg:items-center lg:px-8"><div><h2 className="text-3xl font-black text-white">Ready to run your hotspot professionally?</h2><p className="mt-2 text-blue-50">Create a workspace, receive starter plans and connect your first MikroTik when you are ready.</p></div><Link to="/register" className="inline-flex items-center gap-2 rounded-2xl bg-white px-6 py-4 font-bold text-blue-700 shadow-xl">Create CloudRouter workspace <FiArrowRight/></Link></div></section>
  </main>
  <footer className="bg-blue-950 px-4 py-8 text-center text-sm text-blue-200">© {new Date().getFullYear()} CloudRouter · Hotspot billing, network management and analytics.</footer>
 </div>;}
